### ISSUE TITLE
context.fail() does not allow a user specified message

### ISSUE THREAD

**Issue by maurer** [dwrensha/capnp-rpc-rust#1]
It would be helpful to be able to set the reason field that gets set by fail when fail is called in server code. 

At the moment, "aborted" (https://github.com/dwrensha/capnp-rpc-rust/blob/master/src/rpc.rs#L1159) will be sent every time, resulting in a need to rely on server logs to debug failed RPCs.

**Comment by dwrensha** [comment]
Ok, I've added a `message : String` parameter to the `CallContext.fail()` method. It currently doesn't propagate the message properly for pipelined calls, but it's better than nothing. I think this issue should be left open until it actually works in all cases.

I should also warn you that the RPC side of capnproto-rust is experimental, unstable, buggy, in need of a rewrite, etc. Use at your own risk.

**Comment by dwrensha** [comment]
This is fixed in the upcoming release. RPC methods now return a `gj::Promise<(), ::capnp::Error>`.
