### ISSUE TITLE
Compatibility with Metal IO

### ISSUE THREAD

**Issue by alexchandel** [dwrensha/capnp-rpc-rust#12]
[Metal IO](https://github.com/carllerche/mio) is an interesting library that wraps the various platform-specific polling interfaces. I figure capnp-rpc-rust uses [gj](https://github.com/dwrensha/gj), but I'm wondering how compatible it is with other IO libraries (beyond the `std` ones that gj uses). Or alternatively, whether gj is tied to `std`/compatible with `mio`.

**Comment by dwrensha** [comment]
GJ uses mio as an implementation detail. We could expose the dependency, but I'm not entirely convinced that's the best way forward. See https://github.com/dwrensha/gj/pull/5 for some previous discussion.

Can you elaborate more on what you mean by "compatible"? Do you have any specific use cases in mind?

**Comment by alexchandel** [comment]
Ah I didn't even realize. It might make sense if there are bits of `mio` that can't be used from the EventLoop wrapper you provide.

The particular case I imagined was to use capnp-rpc together with a non-capnp (text-based) rpc, and to run both from an asynchronous event loop (ideally over a pool of threads). It was a bit difficult to tell between [server.rs](https://github.com/dwrensha/capnp-rpc-rust/blob/master/examples/calculator/server.rs) and [echo.rs](https://github.com/dwrensha/gj/blob/master/examples/echo.rs) whether this was possible. Assuming it is, would the non-capnp protocol (and all other IO in the event loop) need to be implemented using promises? That wouldn't necessarily be bad, assuming the boilerplate can be kept to a minimum...

**Comment by burdges** [comment]
At some point I suppose this question becomes about [futures-rs](https://github.com/alexcrichton/futures-rs).

**Comment by dwrensha** [comment]
I see a lot to like in futures-rs, and I can imagine eventually switching to it from gj. If we go that route, there's still the question of what IO library to use: futures-mio, tokio, a port of gjio, something else?

**Comment by burdges** [comment]
I'd imagine being "zero cost" on windows means something like gjio's windows side to futures-rs, no? 

Just noticed this [blog post](https://medium.com/@carllerche/announcing-tokio-df6bb4ddb34#.h4de6fwh4) about [tokio](https://github.com/tokio-rs/tokio) too, which looks interesting.

**Comment by dwrensha** [comment]
Today's release is compatible with tokio/mio: https://dwrensha.github.io/capnproto-rust/2017/01/04/rpc-futures.html
