### ISSUE TITLE
Cannot build capnp-rpc dependency: "capnp compile: -o: missing argument"

### ISSUE THREAD

**Issue by unlikely-leo** [dwrensha/capnp-rpc-rust#14]
Hi, I have minimal project with `capnp-rpc` as a dependency. It doesn't `cargo build`, and I'm not sure why.

The problem should be easy to reproduce. My `Cargo.toml` looks as follows:

```
[package]
name = "hello-rpc"
version = "0.1.0"
authors = ["me <i@myself.com"]

[dependencies]
capnp-rpc = "0.6"
```

```
$ cargo build
   [...]
   Compiling capnp-rpc v0.6.3
failed to run custom build command for `capnp-rpc v0.6.3`
Process didn't exit successfully: `hello-rpc/target/debug/build/capnp-rpc-4dd98f567af5b310/build-script-build` (exit code: 101)
--- stderr
capnp compile: -o: missing argument
Try 'capnp compile --help' for more information.
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Failed, description: "Error while trying to execute `capnp compile`: Failed: Premature EOF.  Perhaps the capnp executable is not installed on your system? See https://capnproto.org/install.html" }', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I have `capnp` version 0.4.0 installed (the latest in Ubuntu 14.04's package repos) -- is `capnp-rpc` only compatible with a later version?

```
$ capnp --version
Cap'n Proto version 0.4.0
```

**Comment by unlikely-leo** [comment]
After building and installing `capnp` version 0.5.3, the error message disappeared. I'm not sure if the documentation mentions which versions of `capnp` this library is compatible with, but perhaps it could be made more immediately visible.

**Comment by unlikely-leo** [comment]
I now realise that this issue is really an issue with `capnpc-rust` -- perhaps the [error handling](https://github.com/dwrensha/capnpc-rust/blob/master/src/lib.rs#L93) could check if the expected version of `capnp` is installed in case of failure and provide a more helpful error message.

**Comment by dwrensha** [comment]
Thanks for the report. I've added the required version number to the error message: https://github.com/dwrensha/capnpc-rust/commit/dc7f0e363d0923456e2f09673fbf3461ea9f2270

**Comment by dwrensha** [comment]
Pushed to crates.io in capnpc v0.6.2.
