### ISSUE TITLE
Using this crate with different transports

### ISSUE THREAD

**Issue by 0nkery** [dwrensha/capnp-rpc-rust#16]
I want to use this crate with `nanomsg`, `mio` and other server or client network libraries. Is it possible? Or this implementation highly coupled with `gj` and `gjio`?

PS. Sorry for newbie question.

**Comment by dwrensha** [comment]
Hi!
To use capnp-rpc-rust, you need to spin up a `gj::EventLoop` and supply a full duplex stream in the form of a `gjio::Read` and a `gjio::Write`. It should be possible to integrate with other networking libraries by writing adapters at `gjio` level. If you tell me more about how you envision using `nanomsg` and `mio` in your application, I might have more to say about how we could improve `gjio` to make such integration easier.

**Comment by 0nkery** [comment]
Hmm, thanks. I need to figure it out in the first place. :)
