### ISSUE TITLE
State of this crate

### ISSUE THREAD

**Issue by 0nkery** [dwrensha/capnp-rpc-rust#17]
Is it up-to-date with reference implementation in C++?
Is it actively maintained?

**Comment by dwrensha** [comment]
Yes, I maintain it.

It's up-to-date in the sense that I am actively using it to develop apps ([1](https://github.com/dwrensha/sandstorm-collections-app), [2](https://github.com/dwrensha/sandstorm-collections-app)) for Sandstorm and it successfully allows those apps to communicate with Sandstorm's C++ and node processes over Cap'n Proto.

It's not up-to-date in the sense that some features are missing, such as full support for [persistent capabilities](https://capnproto.org/rpc.html#protocol-features).

**Comment by 0nkery** [comment]
Thanks! Glad to hear it.
