### ISSUE TITLE
Share object in server implementation

### ISSUE THREAD

**Issue by michaelmior** [dwrensha/capnp-rpc-rust#19]
This may be more of a general Rust question, but I'd appreciate some help. Suppose I have a shared resource that I want to initialize during server setup (e.g. inside `main`) and then access from each function in `CalculatorImpl`. What's the best way to do this?

**Comment by dwrensha** [comment]
I'm not sure that I understand the question. Would it work to add a field to `CalculatorImpl`, containing a reference to the shared resource? Note that RPC methods always have a `&mut self` parameter.

**Comment by michaelmior** [comment]
Yes, adding a field to the struct seems like it will work. Thanks! And thank you for the capnp Rust implementation! Sorry for the noob question :)
