### ISSUE TITLE
Compatibilty with `tokio-proto` and `tokio-service`

### ISSUE THREAD

**Issue by 0nkery** [dwrensha/capnp-rpc-rust#20]
Currently, this crate is compatible with `tokio` and `futures` via `tokio-core` at relatively low-level.

Would it make sense to implement higher-level rpc system based on `tokio-proto` and `tokio-service`?

The main advantage, as I see it, is to have more composable and reusable moving parts that can incorporate (or can be incorporated) with the rest of `tokio` ecosystem.

Or you already have such plans but the main issue in having enough time to refactor everything? :)

**Comment by dwrensha** [comment]
Hi!

My understanding is that the higher-level tokio traits and require everything to fit within a request/response flow. Cap'n Proto RPC is a [complex stateful protocol](https://github.com/sandstorm-io/capnproto/blob/a93eb5f21b54c520bad2a9b44c906e8b5fe42a75/c%2B%2B/src/capnp/rpc.capnp) where not everything tidily fits into pairs of requests and responses, so I'm not sure how we make could use of the tokio traits, or exactly what benefits it would bring if we did.

Do you have in mind any particular patterns of re-use or composition that you want to make sure capnp-rpc supports?

**Comment by 0nkery** [comment]
Middleware - TLS support or logging, for example.

Codecs would be nice example too. I started to implement codecs [btw](https://github.com/0nkery/capnp-rpc-rust/blob/master/src/codec.rs) (unfortunately I didn't have time to implement packed codec due to some health issues). So in short, packed codec can reuse much of functionality of general codec.

Yup, Cap'n Proto RPC is a complex stateful protocol but `tokio` has nice streaming abstractions which can be quite helpful.

Would you be interested to consider such way of implementation? I'll try to come up with something closer to existing impl so we can discuss it more practically.

PS. To clarify - I'm such a newbie in this area, so I'm just asking questions (I hope, not so stupid :)

**Comment by dwrensha** [comment]
Hm. [This bit](https://github.com/0nkery/capnp-rpc-rust/blob/3a53cbd53a0846707c743eef5e587e208119c4da/src/codec.rs#L118-L125) seems to imply an extra copy, and I'm not sure how we could avoid that.

I in general agree that it would be good to evaluate what our options are.

**Comment by 0nkery** [comment]
Okay, I'll inspect that piece of code carefully.

BTW I'm closing issue. Thanks for answers!

PS. What about something like gitter?
