### ISSUE TITLE
Rust RPC client does not work

### ISSUE THREAD

**Issue by spirali** [dwrensha/capnp-rpc-rust#22]
Hello,

I have problem with calling RPC function from Rust.
This is the minimal example I was able to obtain:

I am using the following interface:
```
interface Gate {
    hello @0 () -> (y :Int32);
}
```

and the client code:

```rust
fn client() {
    let mut core = ::tokio_core::reactor::Core::new().unwrap();
    let handle = core.handle();

    let addr = "127.0.0.1:7020".parse().unwrap();
    let connect = TcpStream::connect(&addr, &handle).and_then(move |stream| {
        stream.set_nodelay(true).unwrap();
        println!("Connected");
        let (reader, writer) = stream.split();
        let network = Box::new(twoparty::VatNetwork::new(reader,
                                                         writer,
                                                         rpc_twoparty_capnp::Side::Client,
                                                         Default::default()));
        let mut rpc_system = RpcSystem::new(network, None);

        let gate: ::foo_capnp::gate::Client =
            rpc_system.bootstrap(rpc_twoparty_capnp::Side::Server);
        let req = gate.hello_request();
        let future = req.send()
            .promise
            .and_then(move |response| {
                println!("Finished");
                Promise::ok(())
            })
            .map_err(|e| {
                panic!("Error {}", e);
            });
        future
    });


    core.run(connect).unwrap();
    println!("END");
}

```

The client is connected, but the RPC call is not executed. (It prints "Connected", but not "Finished").
Client waits forever without any error message. The server also sees only connection but no call. 

When I use a testing Python client, it works as expected.

In the attachment, I am including the full example with Rust server/client, and Python client.

Attachment: [cap.tar.gz](https://github.com/dwrensha/capnp-rpc-rust/files/1108544/cap.tar.gz)

**Comment by dwrensha** [comment]
It looks like the problem is that nothing is driving execution of `rpc_system`. You need to make sure that `poll()` gets called on it, as in these examples:

https://github.com/dwrensha/capnp-rpc-rust/blob/bab5fce9f26ff8e3e8660b9079999dece3f8b377/examples/pubsub/client.rs#L75

https://github.com/dwrensha/capnp-rpc-rust/blob/bab5fce9f26ff8e3e8660b9079999dece3f8b377/examples/calculator/client.rs#L75

**Comment by spirali** [comment]
Ahh, I have completely overlooked this despite I use it in the server code.
Thank you, it works now.
