### ISSUE TITLE
comment on security issues with an Internet-facing server?

### ISSUE THREAD

**Issue by ian-p-cooke** [dwrensha/capnp-rpc-rust#26]
re: https://capnproto.org/faq.html (Is it safe to use Cap’n Proto RPC with a malicious peer?)
re: https://capnproto.org/news/2015-03-02-security-advisory-and-integer-overflow-protection.html

Are the security recommendations for the Rust implementation of Cap'n Proto RPC any different than the C++ implementation?  The C++ FAQ is pretty clear that they don't recommend the implementation for malicious clients yet.

The system I have in mind would allow clients to authenticate via Cap'n Proto RPC and then send a capability to the Internet-facing server which would then be used like a plugin to implement their part in a simulation.  The simulation is competitive and there'd be strong incentive to cheat so I anticipate both the authentication and the simulation would be attacked to search for some advantage.

I guess what I'm looking for is a "oh no, don't do that!" or a "it should be ok, but you're on your own." sort of response.

**Comment by dwrensha** [comment]
The Rust implementation is a fairly direct translation of the C++ implementation. The security considerations are similar. Cap'n Proto is designed to be robust against malicious peers, but there still may be bugs.

Any potential resource exhaustion attacks on the C++ RPC implementation (as were alluded to in that FAQ) would probably be applicable to the Rust implementation. Note that there may be operating-system-level ways to mitigate any such attacks -- for example, you could put your internet-facing server in its own sandboxed process.

One way to make the Rust RPC implementation more robust might be to apply some of the fuzzing strategies used for the ocaml implementation: https://groups.google.com/forum/#!msg/capnproto/_1kBtRSC51s/H6tvW0BICAAJ

You should also keep in mind that, at the serialization level, capnproto-rust does use `unsafe` code. See https://github.com/capnproto/capnproto-rust/issues/78. We've done fuzz testing to shake out some bugs there, but there's probably a lot more we could do to lower the likelihood of bugs.

**Comment by ian-p-cooke** [comment]
thanks for the info.  I'll see what specific issues I run into during testing.
