### ISSUE TITLE
RPC Lifetime Issues

### ISSUE THREAD

**Issue by maurer** [dwrensha/capnp-rpc-rust#4]
When using `EzRpcClient`, if you allow it to go out of scope after calling `import_cap()`, the capability will no longer function resulting in SendErrors.

An example is visible in my [Holmes project](https://github.com/BinaryAnalysisPlatform/holmes/blob/rust/server/src/client.rs#L10). If that field (accessed nowhere) is removed, SendErrors result.

I think that making it so that the capabilites resulting from `import_cap()` have a lifetime parameterized by the `EzRpcClient`'s lifetime would fix this issue.

**Comment by dwrensha** [comment]
I think this no longer applies in version 0.6.
